In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('student data.csv')

In [3]:
df

    roll no       Name  Chemistry  Physics  Math
0       101      Aliza         50       23    87
1       102     Fareed         45       24    88
2       103      Basit         46       25    89
3       104   Abdullah         47       26    90
4       105        Ali         48       27    67
5       106   Mubashir         49       28    68
6       107     Waleed         50       29    69
7       108    Mansoor         51       30    70
8       109       Zain         52       31    71
9       110     Mohsin         53       67    72
10      111   Shahmeer         54       68    73
11      112        Rao         55       69    74
12      113  Aurangzeb         56       70    75
13      114    Zeeshan         57       71    76
14      115      Hamna         58       72    77
15      116      Hamza         59       73    78
16      117     Khalid         60       74    79
17      118     Behroz         61       75    80
18      119     Justin         62       76    81
19      120     Danish         63       77    82
20      121     Kainat         64       78    83
21      122     Sameer         65       79    84
22      123       Raza         66       80    85
23      124      Kumar         67       81    86
24      125      Komal         68       82    87
25      126       Erum         69       83    88
26      127      Faiza         70       84    89
27      128      Saeed         71       85    90
28      129      Waqar         72       86    91
29      130       Wali         73       87    92
30      131      Wajid         74       88    93
31      132     Waseeb         75       89    94
32      133      Shiza         76       90    95
33      134    Shabina         77       91    96
34      135    Shazain         78       55    97
35      136      Lubna         79       61    98
36      137      Laiba         80       88    78
37      138  Khursheed         81       56    45
38      139        Ali         82       89    46
39      140       Aiza         83       45    89
40      141      Aiman         84       92    78
41      142    Yasmeen         85       36    56
42      143    Tasbeel         86       78    78
43      144     Laraib         87       56    54
44      145     Saleem         88       78    78
45      146     Bismil         89       89    46
46      147     Batool         90       56    79
47      148       Iqra         91       33    46
48      149    Zarnish         92       78    45
49      150       Zara         83       45    56

In [4]:
df ["Total"] = df["Chemistry"] + df["Physics"] + df["Math"]

In [5]:
df

    roll no       Name  Chemistry  Physics  Math  Total
0       101      Aliza         50       23    87    160
1       102     Fareed         45       24    88    157
2       103      Basit         46       25    89    160
3       104   Abdullah         47       26    90    163
4       105        Ali         48       27    67    142
5       106   Mubashir         49       28    68    145
6       107     Waleed         50       29    69    148
7       108    Mansoor         51       30    70    151
8       109       Zain         52       31    71    154
9       110     Mohsin         53       67    72    192
10      111   Shahmeer         54       68    73    195
11      112        Rao         55       69    74    198
12      113  Aurangzeb         56       70    75    201
13      114    Zeeshan         57       71    76    204
14      115      Hamna         58       72    77    207
15      116      Hamza         59       73    78    210
16      117     Khalid         60       74    79    213
17      118     Behroz         61       75    80    216
18      119     Justin         62       76    81    219
19      120     Danish         63       77    82    222
20      121     Kainat         64       78    83    225
21      122     Sameer         65       79    84    228
22      123       Raza         66       80    85    231
23      124      Kumar         67       81    86    234
24      125      Komal         68       82    87    237
25      126       Erum         69       83    88    240
26      127      Faiza         70       84    89    243
27      128      Saeed         71       85    90    246
28      129      Waqar         72       86    91    249
29      130       Wali         73       87    92    252
30      131      Wajid         74       88    93    255
31      132     Waseeb         75       89    94    258
32      133      Shiza         76       90    95    261
33      134    Shabina         77       91    96    264
34      135    Shazain         78       55    97    230
35      136      Lubna         79       61    98    238
36      137      Laiba         80       88    78    246
37      138  Khursheed         81       56    45    182
38      139        Ali         82       89    46    217
39      140       Aiza         83       45    89    217
40      141      Aiman         84       92    78    254
41      142    Yasmeen         85       36    56    177
42      143    Tasbeel         86       78    78    242
43      144     Laraib         87       56    54    197
44      145     Saleem         88       78    78    244
45      146     Bismil         89       89    46    224
46      147     Batool         90       56    79    225
47      148       Iqra         91       33    46    170
48      149    Zarnish         92       78    45    215
49      150       Zara         83       45    56    184

In [10]:
df["Percentage"] = round((df["Total"]/300)*100)

In [11]:
df

    roll no       Name  Chemistry  Physics  Math  Total  Percentage
0       101      Aliza         50       23    87    160        53.0
1       102     Fareed         45       24    88    157        52.0
2       103      Basit         46       25    89    160        53.0
3       104   Abdullah         47       26    90    163        54.0
4       105        Ali         48       27    67    142        47.0
5       106   Mubashir         49       28    68    145        48.0
6       107     Waleed         50       29    69    148        49.0
7       108    Mansoor         51       30    70    151        50.0
8       109       Zain         52       31    71    154        51.0
9       110     Mohsin         53       67    72    192        64.0
10      111   Shahmeer         54       68    73    195        65.0
11      112        Rao         55       69    74    198        66.0
12      113  Aurangzeb         56       70    75    201        67.0
13      114    Zeeshan         57       71    76    204        68.0
14      115      Hamna         58       72    77    207        69.0
15      116      Hamza         59       73    78    210        70.0
16      117     Khalid         60       74    79    213        71.0
17      118     Behroz         61       75    80    216        72.0
18      119     Justin         62       76    81    219        73.0
19      120     Danish         63       77    82    222        74.0
20      121     Kainat         64       78    83    225        75.0
21      122     Sameer         65       79    84    228        76.0
22      123       Raza         66       80    85    231        77.0
23      124      Kumar         67       81    86    234        78.0
24      125      Komal         68       82    87    237        79.0
25      126       Erum         69       83    88    240        80.0
26      127      Faiza         70       84    89    243        81.0
27      128      Saeed         71       85    90    246        82.0
28      129      Waqar         72       86    91    249        83.0
29      130       Wali         73       87    92    252        84.0
30      131      Wajid         74       88    93    255        85.0
31      132     Waseeb         75       89    94    258        86.0
32      133      Shiza         76       90    95    261        87.0
33      134    Shabina         77       91    96    264        88.0
34      135    Shazain         78       55    97    230        77.0
35      136      Lubna         79       61    98    238        79.0
36      137      Laiba         80       88    78    246        82.0
37      138  Khursheed         81       56    45    182        61.0
38      139        Ali         82       89    46    217        72.0
39      140       Aiza         83       45    89    217        72.0
40      141      Aiman         84       92    78    254        85.0
41      142    Yasmeen         85       36    56    177        59.0
42      143    Tasbeel         86       78    78    242        81.0
43      144     Laraib         87       56    54    197        66.0
44      145     Saleem         88       78    78    244        81.0
45      146     Bismil         89       89    46    224        75.0
46      147     Batool         90       56    79    225        75.0
47      148       Iqra         91       33    46    170        57.0
48      149    Zarnish         92       78    45    215        72.0
49      150       Zara         83       45    56    184        61.0

In [16]:
def get_grade(Percentage):
    if Percentage >= 80 and Percentage <= 100:
        return "A"
    elif Percentage >= 70 and Percentage <= 80:
        return "B"
    elif Percentage >= 60 and Percentage <= 70:
        return "C"
    elif Percentage >= 50 and Percentage <= 60:
        return "D"
    else:
        return "Fail"

In [17]:
df["Grade"] = df["Percentage"].apply(get_grade)

In [18]:
df

    roll no       Name  Chemistry  Physics  Math  Total  Percentage Grade
0       101      Aliza         50       23    87    160        53.0     D
1       102     Fareed         45       24    88    157        52.0     D
2       103      Basit         46       25    89    160        53.0     D
3       104   Abdullah         47       26    90    163        54.0     D
4       105        Ali         48       27    67    142        47.0  Fail
5       106   Mubashir         49       28    68    145        48.0  Fail
6       107     Waleed         50       29    69    148        49.0  Fail
7       108    Mansoor         51       30    70    151        50.0     D
8       109       Zain         52       31    71    154        51.0     D
9       110     Mohsin         53       67    72    192        64.0     C
10      111   Shahmeer         54       68    73    195        65.0     C
11      112        Rao         55       69    74    198        66.0     C
12      113  Aurangzeb         56       70    75    201        67.0     C
13      114    Zeeshan         57       71    76    204        68.0     C
14      115      Hamna         58       72    77    207        69.0     C
15      116      Hamza         59       73    78    210        70.0     B
16      117     Khalid         60       74    79    213        71.0     B
17      118     Behroz         61       75    80    216        72.0     B
18      119     Justin         62       76    81    219        73.0     B
19      120     Danish         63       77    82    222        74.0     B
20      121     Kainat         64       78    83    225        75.0     B
21      122     Sameer         65       79    84    228        76.0     B
22      123       Raza         66       80    85    231        77.0     B
23      124      Kumar         67       81    86    234        78.0     B
24      125      Komal         68       82    87    237        79.0     B
25      126       Erum         69       83    88    240        80.0     A
26      127      Faiza         70       84    89    243        81.0     A
27      128      Saeed         71       85    90    246        82.0     A
28      129      Waqar         72       86    91    249        83.0     A
29      130       Wali         73       87    92    252        84.0     A
30      131      Wajid         74       88    93    255        85.0     A
31      132     Waseeb         75       89    94    258        86.0     A
32      133      Shiza         76       90    95    261        87.0     A
33      134    Shabina         77       91    96    264        88.0     A
34      135    Shazain         78       55    97    230        77.0     B
35      136      Lubna         79       61    98    238        79.0     B
36      137      Laiba         80       88    78    246        82.0     A
37      138  Khursheed         81       56    45    182        61.0     C
38      139        Ali         82       89    46    217        72.0     B
39      140       Aiza         83       45    89    217        72.0     B
40      141      Aiman         84       92    78    254        85.0     A
41      142    Yasmeen         85       36    56    177        59.0     D
42      143    Tasbeel         86       78    78    242        81.0     A
43      144     Laraib         87       56    54    197        66.0     C
44      145     Saleem         88       78    78    244        81.0     A
45      146     Bismil         89       89    46    224        75.0     B
46      147     Batool         90       56    79    225        75.0     B
47      148       Iqra         91       33    46    170        57.0     D
48      149    Zarnish         92       78    45    215        72.0     B
49      150       Zara         83       45    56    184        61.0     C

In [19]:
df.to_csv("students_with_grades.csv", index=False)