In [1]:
import pandas as pd
import sqlite3 as sql

In [12]:
conn = sql.connect('factbook.db')
conn

In [13]:
def sql_query (q):
    return pd.read_sql_query(q,conn)

In [20]:
q = 'select *from sqlite_master'
q

'select *from sqlite_master'

In [21]:
sql_query(q)

,type,name,tbl_name,rootpage,sql
0,table,sqlite_sequence,sqlite_sequence,3,"CREATE TABLE sqlite_sequence(name,seq)"
1,table,facts,facts,47,"CREATE TABLE ""facts"" (""id"" INTEGER PRIMARY KEY..."
2,table,cities,cities,2,CREATE TABLE cities (\n id integer prim...

In [23]:
q='pragma table_info (facts)'
sql_query(q)

    cid               name          type  notnull dflt_value  pk
0     0                 id       INTEGER        1       None   1
1     1               code  varchar(255)        1       None   0
2     2               name  varchar(255)        1       None   0
3     3               area       INTEGER        0       None   0
4     4          area_land       INTEGER        0       None   0
5     5         area_water       INTEGER        0       None   0
6     6         population       INTEGER        0       None   0
7     7  population_growth         float        0       None   0
8     8         birth_rate         float        0       None   0
9     9         death_rate         float        0       None   0
10   10     migration_rate         float        0       None   0

In [24]:
q='pragma table_info (cities)'
sql_query(q)

   cid        name     type  notnull dflt_value  pk
0    0          id  INTEGER        0       None   1
1    1        name     TEXT        0       None   0
2    2  population  INTEGER        0       None   0
3    3     capital     bool        0       None   0
4    4    facts_id     TEXT        0       None   0

In [25]:
q = 'select * from facts'
sql_query(q)

,id,code,name,area,area_land,area_water,population,population_growth,birth_rate,death_rate,migration_rate
0,1,af,Afghanistan,652230.0,652230.0,0.0,3.256434e+07,2.32,38.57,13.89,1.51
1,2,al,Albania,28748.0,27398.0,1350.0,3.029278e+06,0.30,12.92,6.58,3.30
2,3,ag,Algeria,2381741.0,2381741.0,0.0,3.954217e+07,1.84,23.67,4.31,0.92
3,4,an,Andorra,468.0,468.0,0.0,8.558000e+04,0.12,8.13,6.96,0.00
4,5,ao,Angola,1246700.0,1246700.0,0.0,1.962535e+07,2.78,38.78,11.49,0.46
...,...,...,...,...,...,...,...,...,...,...,...
256,257,zh,Atlantic Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,258,xo,Indian Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,259,zn,Pacific Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,260,oo,Southern Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,261,xx,World,NaN,NaN,NaN,7.256490e+09,1.08,18.60,7.80,NaN

In [27]:
q = 'select * from cities'
sql_query(q)

      id          name  population  capital facts_id
0      1    Oranjestad       37000        1      216
1      2  Saint John'S       27000        1        6
2      3     Abu Dhabi      942000        1      184
3      4         Dubai     1978000        0      184
4      5       Sharjah      983000        0      184
..   ...           ...         ...      ...      ...
392  393       Mbabane       66000        1      167
393  394         Sanaa     2419000        1      193
394  395          Aden      784000        0      193
395  396        Lusaka     1802000        1      194
396  397        Harare     1542000        1      195

[397 rows x 5 columns]

In [45]:
q = 'select * from facts inner join cities on facts.id = cities.facts_id'
sql_query(q)

,id,code,name,area,area_land,area_water,population,population_growth,birth_rate,death_rate,migration_rate,id,name,population,capital,facts_id
0,216,aa,Aruba,180.0,180.0,0.0,112162,1.33,12.56,8.18,8.92,1,Oranjestad,37000,1,216
1,6,ac,Antigua and Barbuda,442.0,442.0,0.0,92436,1.24,15.85,5.69,2.21,2,Saint John'S,27000,1,6
2,184,ae,United Arab Emirates,83600.0,83600.0,0.0,5779760,2.58,15.43,1.97,12.36,3,Abu Dhabi,942000,1,184
3,184,ae,United Arab Emirates,83600.0,83600.0,0.0,5779760,2.58,15.43,1.97,12.36,4,Dubai,1978000,0,184
4,184,ae,United Arab Emirates,83600.0,83600.0,0.0,5779760,2.58,15.43,1.97,12.36,5,Sharjah,983000,0,184
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,167,wz,Swaziland,17364.0,17204.0,160.0,1435613,1.11,24.67,13.56,0.00,393,Mbabane,66000,1,167
393,193,ym,Yemen,527968.0,527968.0,0.0,26737317,2.47,29.98,6.28,1.00,394,Sanaa,2419000,1,193
394,193,ym,Yemen,527968.0,527968.0,0.0,26737317,2.47,29.98,6.28,1.00,395,Aden,784000,0,193
395,194,za,Zambia,752618.0,743398.0,9220.0,15066266,2.88,42.13,12.67,0.68,396,Lusaka,1802000,1,194
396,195,zi,Zimbabwe,390757.0,386847.0,3910.0,14229541,2.21,32.26,10.13,0.00,397,Harare,1542000,1,195

1. List all cities where the area is greater than 5000, along with their population.

In [44]:
q = 'Select *from cities where population > 5000'
sql_query (q)

      id          name  population  capital facts_id
0      1    Oranjestad       37000        1      216
1      2  Saint John'S       27000        1        6
2      3     Abu Dhabi      942000        1      184
3      4         Dubai     1978000        0      184
4      5       Sharjah      983000        0      184
..   ...           ...         ...      ...      ...
384  393       Mbabane       66000        1      167
385  394         Sanaa     2419000        1      193
386  395          Aden      784000        0      193
387  396        Lusaka     1802000        1      194
388  397        Harare     1542000        1      195

[389 rows x 5 columns]

2. List the names of capital cities where the death rate is greater than 2% and the
birth rate is less than 20%

In [52]:
q = '''
SELECT cities.name
FROM facts
INNER JOIN cities
    ON facts.id = cities.facts_id
WHERE cities.capital = 1
  AND facts.death_rate > 2
  AND facts.birth_rate < 20
'''

sql_query(q)

                 name
0          Oranjestad
1        Saint John'S
2                Baku
3              Tirana
4             Yerevan
..                ...
123         Road Town
124             Hanoi
125  Charlotte Amalie
126          Windhoek
127          Mata-Utu

[128 rows x 1 columns]

In [53]:
q = '''
SELECT cities.name,
       facts.death_rate,
       facts.birth_rate
FROM facts
INNER JOIN cities
    ON facts.id = cities.facts_id
WHERE cities.capital = 1
  AND facts.death_rate > 2
  AND facts.birth_rate < 20
'''

sql_query(q)

                 name  death_rate  birth_rate
0          Oranjestad        8.18       12.56
1        Saint John'S        5.69       15.85
2                Baku        7.07       16.64
3              Tirana        6.58       12.92
4             Yerevan        9.34       13.61
..                ...         ...         ...
123         Road Town        4.99       10.91
124             Hanoi        5.93       15.96
125  Charlotte Amalie        8.54       10.31
126          Windhoek       13.91       19.80
127          Mata-Utu        5.06       13.45

[128 rows x 3 columns]

In [54]:
q = '''
SELECT facts.name AS country,
       cities.name AS capital_city,
       facts.death_rate,
       facts.birth_rate
FROM facts
INNER JOIN cities
    ON facts.id = cities.facts_id
WHERE cities.capital = 1
  AND facts.death_rate > 2
  AND facts.birth_rate < 20
'''

sql_query(q)

                    country      capital_city  death_rate  birth_rate
0                     Aruba        Oranjestad        8.18       12.56
1       Antigua and Barbuda      Saint John'S        5.69       15.85
2                Azerbaijan              Baku        7.07       16.64
3                   Albania            Tirana        6.58       12.92
4                   Armenia           Yerevan        9.34       13.61
..                      ...               ...         ...         ...
123  British Virgin Islands         Road Town        4.99       10.91
124                 Vietnam             Hanoi        5.93       15.96
125          Virgin Islands  Charlotte Amalie        8.54       10.31
126                 Namibia          Windhoek       13.91       19.80
127       Wallis and Futuna          Mata-Utu        5.06       13.45

[128 rows x 4 columns]

In [55]:
q = '''
SELECT facts.name AS country,
       cities.name AS capital_city,
       facts.death_rate,
       facts.birth_rate
FROM facts
INNER JOIN cities
    ON facts.id = cities.facts_id
WHERE facts.name = 'Pakistan'
  AND cities.name = 'Islamabad'
'''

sql_query(q)

    country capital_city  death_rate  birth_rate
0  Pakistan    Islamabad        6.49       22.58

3. List the cities with a population growth rate between 1% and 5%, sorted in desc
by population growth.

In [56]:
q = '''select name, population_growth from facts 
where population_growth between 1 and 5
order by population_growth desc'''
sql_query(q)

            name  population_growth
0    South Sudan               4.02
1         Malawi               3.32
2        Burundi               3.28
3          Niger               3.25
4         Uganda               3.24
..           ...                ...
119    Lithuania               1.04
120      Moldova               1.03
121        Burma               1.01
122      Morocco               1.00
123    Nicaragua               1.00

[124 rows x 2 columns]

In [57]:
q = '''select facts.name AS country, name, population_growth from facts 
where population_growth between 1 and 5
order by population_growth desc'''
sql_query(q)

         country         name  population_growth
0    South Sudan  South Sudan               4.02
1         Malawi       Malawi               3.32
2        Burundi      Burundi               3.28
3          Niger        Niger               3.25
4         Uganda       Uganda               3.24
..           ...          ...                ...
119    Lithuania    Lithuania               1.04
120      Moldova      Moldova               1.03
121        Burma        Burma               1.01
122      Morocco      Morocco               1.00
123    Nicaragua    Nicaragua               1.00

[124 rows x 3 columns]

In [58]:
q = '''
SELECT facts.name AS country,
       cities.name AS city,
       facts.population_growth
FROM facts
INNER JOIN cities
    ON facts.id = cities.facts_id
WHERE facts.name = 'Pakistan'
  AND cities.name = 'Islamabad'
  AND facts.population_growth BETWEEN 1 AND 5
ORDER BY facts.population_growth DESC
'''

sql_query(q)

    country       city  population_growth
0  Pakistan  Islamabad               1.46

##### 4. Find countries that start with &quot;A&quot; and do not have any cities listed in the cities table. The query should return the country name and city name. Using left join.

In [59]:
q = '''
select facts.name as country, cities.name as city
from facts left join cities ON facts.id = cities.facts_id
WHERE facts.name LIKE 'A%' AND cities.name IS NULL'''
sql_query(q)

                       country  city
0  Ashmore and Cartier Islands  None
1                     Akrotiri  None
2                   Antarctica  None
3                 Arctic Ocean  None
4               Atlantic Ocean  None

In [60]:
q = '''
SELECT facts.name AS country,
       cities.name AS city
FROM facts
LEFT JOIN cities
    ON facts.id = cities.facts_id
WHERE facts.name LIKE 'A%'
'''

sql_query(q)

                        country                   city
0                   Afghanistan                  Kabul
1                       Albania                 Tirana
2                       Algeria                Algiers
3                       Algeria                   Oran
4                       Andorra       Andorra La Vella
5                        Angola                 Luanda
6                        Angola                 Huambo
7           Antigua and Barbuda           Saint John'S
8                     Argentina           Buenos Aires
9                     Argentina                Cordoba
10                    Argentina                Rosario
11                    Argentina                Mendoza
12                    Argentina  San Miguel de Tucuman
13                    Argentina               La Plata
14                      Armenia                Yerevan
15                    Australia                 Sydney
16                    Australia              Melbourne
17                    Australia               Brisbane
18                    Australia                  Perth
19                    Australia               Adelaide
20                    Australia               Canberra
21                      Austria                 Vienna
22                   Azerbaijan                   Baku
23  Ashmore and Cartier Islands                   None
24                        Aruba             Oranjestad
25                     Akrotiri                   None
26                     Anguilla             The Valley
27               American Samoa              Pago Pago
28                   Antarctica                   None
29                 Arctic Ocean                   None
30               Atlantic Ocean                   None

In [61]:
q = '''
SELECT facts.name AS country,
       cities.name AS city
FROM facts
LEFT JOIN cities
    ON facts.id = cities.facts_id
WHERE cities.name IS NULL
'''

sql_query(q)

                                          country  city
0                                          Kosovo  None
1                                          Monaco  None
2                                           Nauru  None
3                                      San Marino  None
4                                       Singapore  None
5                         Holy See (Vatican City)  None
6                                          Taiwan  None
7                                  European Union  None
8                     Ashmore and Cartier Islands  None
9                                Christmas Island  None
10                        Cocos (Keeling) Islands  None
11                              Coral Sea Islands  None
12              Heard Island and McDonald Islands  None
13                                 Norfolk Island  None
14                                      Hong Kong  None
15                                          Macau  None
16                              Clipperton Island  None
17            French Southern and Antarctic Lands  None
18                               Saint Barthelemy  None
19                                   Saint Martin  None
20                                        Curacao  None
21                                   Sint Maarten  None
22                                   Cook Islands  None
23                                           Niue  None
24                                        Tokelau  None
25                                  Bouvet Island  None
26                                      Jan Mayen  None
27                                       Svalbard  None
28                                       Akrotiri  None
29                 British Indian Ocean Territory  None
30                                       Dhekelia  None
31                                      Gibraltar  None
32                                       Guernsey  None
33                                         Jersey  None
34                                     Montserrat  None
35                               Pitcairn Islands  None
36       South Georgia and South Sandwich Islands  None
37                                 Navassa Island  None
38                                    Wake Island  None
39  United States Pacific Island Wildlife Refuges  None
40                                     Antarctica  None
41                                     Gaza Strip  None
42                                Paracel Islands  None
43                                Spratly Islands  None
44                                      West Bank  None
45                                   Arctic Ocean  None
46                                 Atlantic Ocean  None
47                                   Indian Ocean  None
48                                  Pacific Ocean  None
49                                 Southern Ocean  None
50                                          World  None

5. List all capital cities and their corresponding death rate using a LEFT JOIN.

In [62]:
q = '''Select cities.name AS capital_city, facts.death_rate
FROM cities LEFT JOIN facts ON cities.facts_id = facts.id
WHERE cities.capital = 1 '''
sql_query(q)

     capital_city  death_rate
0      Oranjestad        8.18
1    Saint John'S        5.69
2       Abu Dhabi        1.97
3           Kabul       13.89
4         Algiers        4.31
..            ...         ...
203          Apia        5.32
204       Mbabane       13.56
205         Sanaa        6.28
206        Lusaka       12.67
207        Harare       10.13

[208 rows x 2 columns]